name: Upload EduHelpdesk Release Asset

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find latest ZIP
        id: find_zip
        run: |
          latest=$(ls Release/*.zip | sort -V | tail -n 1)
          echo "latest_zip=$latest" >> $GITHUB_OUTPUT

      - name: Upload latest ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.find_zip.outputs.latest_zip }}
          asset_name: ${{ steps.find_zip.outputs.latest_zip }}
          asset_content_type: application/zip
